/**
 * Nongoeuskara — interactive municipality map of Euskal Herria.
 *
 * map.svg is generated by build/build_map.py from real GeoJSON boundaries:
 * every municipality is one named <path class="mun"> with `data-name` and
 * (for the 430 Ahotsak towns) a `data-model-label` matching one of the 12
 * tier-3 azpieuskalki model classes. Single coordinate system, no transforms,
 * no inline styles.
 *
 * Highlighting is pure CSS: we set `data-active-label` on the <svg> root and
 * a generated stylesheet colors the matching municipalities. O(1) per update,
 * with smooth fill transitions.
 */

const MODEL_LABELS = {
  "mendebal-sartaldea":   { name: "Mendebal-sartaldea",   color: "#8b5cf6" },
  "mendebal-sortaldea":   { name: "Mendebal-sortaldea",   color: "#7c3aed" },
  "erdialde-sartaldea":   { name: "Erdialde-sartaldea",   color: "#06b6d4" },
  "erdialde-sortaldea":   { name: "Erdialde-sortaldea",   color: "#0ea5e9" },
  "nafar-ipar-sartaldea": { name: "Nafar ipar-sartaldea", color: "#f59e0b" },
  "nafar-erdigunea":      { name: "Nafar erdigunea",      color: "#10b981" },
  "nafar-hego-sartaldea": { name: "Nafar hego-sartaldea", color: "#84cc16" },
  "nafar-sortaldea":      { name: "Nafar sortaldea",      color: "#f97316" },
  "naflap-sartaldea":     { name: "Naf-lapur sartaldea",  color: "#ec4899" },
  "naflap-sortaldea":     { name: "Naf-lapur sortaldea",  color: "#d946ef" },
  "zuberera":             { name: "Zuberera",             color: "#14b8a6" },
  "ekialde-nafarra":      { name: "Ekialdeko nafarra",    color: "#ef4444" },
};

const container = document.getElementById("mapContainer");
const tooltip = document.getElementById("tooltip");
const badge = document.getElementById("predictionBadge");
const badgeSwatch = document.getElementById("predictionSwatch");
const badgeName = document.getElementById("predictionName");
const badgeSecondary = document.getElementById("predictionSecondary");
const mapHint = document.getElementById("mapHint");

let svgRoot = null;

/** Build the stylesheet that drives all map states. */
function buildMapStyles() {
  const rules = [
    `.mun {
       fill: var(--map-mun-fill, #d8dde2);
       stroke: var(--map-mun-stroke, #b8c0c8);
       stroke-width: 0.4;
       transition: fill 0.25s ease, fill-opacity 0.25s ease;
       cursor: default;
     }`,
    `.province {
       fill: none;
       stroke: var(--map-province-stroke, #8a949e);
       stroke-width: 1.1;
       stroke-linejoin: round;
       pointer-events: none;
     }`,
    // hovered municipality outline (any state)
    `.mun:hover {
       stroke: var(--color-accent, #e85d75);
       stroke-width: 1;
     }`,
  ];

  for (const [label, info] of Object.entries(MODEL_LABELS)) {
    // runner-up zone: same color, faint (rule first so active wins on ties)
    rules.push(
      `svg[data-secondary-label="${label}"] .mun[data-model-label="${label}"] {
         fill: ${info.color};
         fill-opacity: 0.3;
         stroke: ${info.color};
         stroke-opacity: 0.4;
       }`
    );
    // active zone: full color
    rules.push(
      `svg[data-active-label="${label}"] .mun[data-model-label="${label}"] {
         fill: ${info.color};
         fill-opacity: 0.9;
         stroke: ${info.color};
       }`
    );
  }
  // while a zone is active, dim everything else slightly so the zone pops
  rules.push(
    `svg[data-active-label] .mun:not([data-model-label]) { fill-opacity: 0.55; }`
  );

  const style = document.createElement("style");
  style.id = "map-styles";
  style.textContent = rules.join("\n");
  return style;
}

function getZoneName(label) {
  return MODEL_LABELS[label]?.name || null;
}

function moveTooltip(event) {
  const pad = 14;
  let x = event.clientX + pad;
  let y = event.clientY + pad;
  const rect = tooltip.getBoundingClientRect();
  if (x + rect.width > window.innerWidth - 8) x = event.clientX - rect.width - pad;
  if (y + rect.height > window.innerHeight - 8) y = event.clientY - rect.height - pad;
  tooltip.style.left = `${x}px`;
  tooltip.style.top = `${y}px`;
}

function showTooltip(path, event) {
  const name = path.dataset.name;
  if (!name) return;
  const zone = getZoneName(path.dataset.modelLabel);
  tooltip.innerHTML = "";
  const strong = document.createElement("strong");
  strong.textContent = name;
  tooltip.appendChild(strong);
  if (zone) {
    const span = document.createElement("span");
    span.textContent = ` · ${zone}`;
    span.style.opacity = "0.65";
    tooltip.appendChild(span);
  }
  tooltip.classList.add("visible");
  moveTooltip(event);
}

async function loadMap() {
  const resp = await fetch(new URL("../map.svg", import.meta.url));
  container.innerHTML = await resp.text();
  svgRoot = container.querySelector("svg");
  if (!svgRoot) return;

  document.head.appendChild(buildMapStyles());

  // Event delegation: paths never overlap, so e.target is THE municipality.
  svgRoot.addEventListener("pointermove", (e) => {
    const path = e.target.closest?.(".mun");
    if (path) {
      showTooltip(path, e);
    } else {
      tooltip.classList.remove("visible");
    }
  });

  svgRoot.addEventListener("pointerleave", () => {
    tooltip.classList.remove("visible");
  });

  if (mapHint) {
    svgRoot.addEventListener("pointerover", () => {
      mapHint.style.display = "none";
    }, { once: true });
  }
}

/**
 * Highlight every municipality belonging to a model label. O(1).
 * An optional runner-up label is shown in the same color at low opacity.
 */
function highlightLabel(modelLabel, secondaryLabel) {
  if (!svgRoot) return;
  if (MODEL_LABELS[modelLabel]) {
    svgRoot.setAttribute("data-active-label", modelLabel);
  } else {
    svgRoot.removeAttribute("data-active-label");
  }
  if (MODEL_LABELS[secondaryLabel] && secondaryLabel !== modelLabel) {
    svgRoot.setAttribute("data-secondary-label", secondaryLabel);
  } else {
    svgRoot.removeAttribute("data-secondary-label");
  }
}

function clearHighlight() {
  if (svgRoot) {
    svgRoot.removeAttribute("data-active-label");
    svgRoot.removeAttribute("data-secondary-label");
  }
  if (badge) badge.classList.remove("visible");
}

/** Highlight the predicted zone(s) and show them in the header badge. */
function pinLabel(modelLabel, secondaryLabel, confidence) {
  highlightLabel(modelLabel, secondaryLabel);
  const info = MODEL_LABELS[modelLabel];
  if (info && badge && badgeSwatch && badgeName) {
    badgeSwatch.style.backgroundColor = info.color;
    const pct = confidence != null ? ` (${(confidence * 100).toFixed(0)}%)` : "";
    badgeName.textContent = info.name + pct;
    const secondary = MODEL_LABELS[secondaryLabel];
    if (badgeSecondary) {
      badgeSecondary.textContent =
        secondary && secondaryLabel !== modelLabel ? `· ${secondary.name}?` : "";
    }
    badge.classList.add("visible");
  }
}

loadMap();

// Public API for model integration
window.euskalkid = {
  highlightLabel,
  clearHighlight,
  pinLabel,
  MODEL_LABELS,
};
